services:
  valkey-1:
    image: valkey/valkey:latest
    container_name: valkey-1
    network_mode: host
    volumes:
      - ../tmp/valkey/valkey-1:/data
      - ./valkey.conf:/usr/local/etc/valkey/valkey.conf:ro
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf", "--port", "7101", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7101", "--cluster-announce-bus-port", "17101"]

  valkey-2:
    image: valkey/valkey:latest
    container_name: valkey-2
    network_mode: host
    volumes:
      - ../tmp/valkey/valkey-2:/data
      - ./valkey.conf:/usr/local/etc/valkey/valkey.conf:ro
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf", "--port", "7102", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7102", "--cluster-announce-bus-port", "17102"]

  valkey-3:
    image: valkey/valkey:latest
    container_name: valkey-3
    network_mode: host
    volumes:
      - ../tmp/valkey/valkey-3:/data
      - ./valkey.conf:/usr/local/etc/valkey/valkey.conf:ro
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf", "--port", "7103", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7103", "--cluster-announce-bus-port", "17103"]

  valkey-4:
    image: valkey/valkey:latest
    container_name: valkey-4
    network_mode: host
    volumes:
      - ../tmp/valkey/valkey-4:/data
      - ./valkey.conf:/usr/local/etc/valkey/valkey.conf:ro
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf", "--port", "7104", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7104", "--cluster-announce-bus-port", "17104"]

  valkey-5:
    image: valkey/valkey:latest
    container_name: valkey-5
    network_mode: host
    volumes:
      - ../tmp/valkey/valkey-5:/data
      - ./valkey.conf:/usr/local/etc/valkey/valkey.conf:ro
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf", "--port", "7105", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7105", "--cluster-announce-bus-port", "17105"]

  valkey-6:
    image: valkey/valkey:latest
    container_name: valkey-6
    network_mode: host
    volumes:
      - ../tmp/valkey/valkey-6:/data
      - ./valkey.conf:/usr/local/etc/valkey/valkey.conf:ro
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf", "--port", "7106", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7106", "--cluster-announce-bus-port", "17106"]

  valkey-cluster-init:
    image: valkey/valkey:latest
    container_name: valkey-cluster-init
    network_mode: host
    depends_on:
      - valkey-1
      - valkey-2
      - valkey-3
      - valkey-4
      - valkey-5
      - valkey-6
    command: >
      sh -c "sleep 5 &&
      echo yes | valkey-cli -a foobared --cluster create
      127.0.0.1:7101 127.0.0.1:7102 127.0.0.1:7103
      127.0.0.1:7104 127.0.0.1:7105 127.0.0.1:7106
      --cluster-replicas 1"
