services:
  redis-1:
    image: redis:latest
    container_name: redis-1
    network_mode: host
    volumes:
      - ../tmp/redis/redis-1:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7001", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7001", "--cluster-announce-bus-port", "17001"]
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M

  redis-2:
    image: redis:latest
    container_name: redis-2
    network_mode: host
    volumes:
      - ../tmp/redis/redis-2:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7002", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7002", "--cluster-announce-bus-port", "17002"]
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M

  redis-3:
    image: redis:latest
    container_name: redis-3
    network_mode: host
    volumes:
      - ../tmp/redis/redis-3:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7003", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7003", "--cluster-announce-bus-port", "17003"]
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M

  redis-4:
    image: redis:latest
    container_name: redis-4
    network_mode: host
    volumes:
      - ../tmp/redis/redis-4:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7004", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7004", "--cluster-announce-bus-port", "17004"]
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M

  redis-5:
    image: redis:latest
    container_name: redis-5
    network_mode: host
    volumes:
      - ../tmp/redis/redis-5:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7005", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7005", "--cluster-announce-bus-port", "17005"]
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M

  redis-6:
    image: redis:latest
    container_name: redis-6
    network_mode: host
    volumes:
      - ../tmp/redis/redis-6:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7006", "--cluster-announce-ip", "127.0.0.1", "--cluster-announce-port", "7006", "--cluster-announce-bus-port", "17006"]
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M

  redis-cluster-init:
    image: redis:latest
    container_name: redis-cluster-init
    network_mode: host
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    command: >
      sh -c "sleep 5 &&
      echo yes | redis-cli -a foobared --cluster create
      127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003
      127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006
      --cluster-replicas 1"
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 24M
